# Generated by Django 3.2.3 on 2021-06-01 17:21

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_auto_20210601_2239'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='datetime',
            field=models.DateTimeField(default=datetime.datetime(2021, 6, 1, 17, 21, 6, 131023, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='like',
            name='datetime',
            field=models.DateTimeField(default=datetime.datetime(2021, 6, 1, 17, 21, 6, 130026, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='post',
            name='datetime',
            field=models.DateTimeField(default=datetime.datetime(2021, 6, 1, 17, 21, 6, 129028, tzinfo=utc)),
        ),
    ]
