# Generated by Django 3.2.3 on 2021-06-03 19:18

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_auto_20210601_2251'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='likes',
        ),
        migrations.AlterField(
            model_name='comment',
            name='datetime',
            field=models.DateTimeField(default=datetime.datetime(2021, 6, 3, 19, 18, 39, 257884, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='like',
            name='datetime',
            field=models.DateTimeField(default=datetime.datetime(2021, 6, 3, 19, 18, 39, 256887, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='post',
            name='datetime',
            field=models.DateTimeField(default=datetime.datetime(2021, 6, 3, 19, 18, 39, 255889, tzinfo=utc)),
        ),
    ]
